name: ac_dart_essentials
description: Dart Essentials
version: 0.1.0
repository: https://github.com/anthochamp/dart-essentials

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  async: ^2.10.0
  characters: ^1.2.1
  collection: ^1.17.0

dev_dependencies:
  anthochamp_lints:
    git: git@github.com:anthochamp/dart-lints.git
  dart_code_metrics: ^5.7.2
  import_sorter: ^4.6.0
  lints: ^2.0.1
  test: ^1.24.2
