name: anthochamp_dart_essentials
version: 1.0.0
repository: https://github.com/anthochamp/dart-essentials

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  async: ^2.11.0
  characters: ^1.3.0
  collection: ^1.17.1

dev_dependencies:
  anthochamp_lints:
    git: git@github.com:anthochamp/dart-lints.git
  dart_code_metrics: ^5.7.2
  lints: ^2.0.1
  test: ^1.24.2
