name: ac_dart_essentials
description: AC Dart Essentials
version: 0.2.2
repository: https://github.com/anthochamp/dart-essentials

environment:
  sdk: '>=2.19.5 <4.0.0'

dependencies:
  async: ^2.10.0
  characters: ^1.2.1
  collection: ^1.17.0

dev_dependencies:
  ac_lints: ^0.4.0
  import_sorter: ^4.6.0
  test: ^1.24.2
